$ErrorActionPreference='Stop'
function Col([int]$n){$s='';while($n-gt0){$n--;$s=[char](65+($n%26))+$s;$n=[math]::Floor($n/26)};$s}
function G([string[]]$p,[hashtable]$q){$j=$q|ConvertTo-Json -Compress -Depth 8;$r=& gws @p --params $j --format json 2>$null;if($LASTEXITCODE-ne0){throw'gws'};($r-join"`n")|ConvertFrom-Json -Depth 100}
$books=[ordered]@{
 sw_fin=@{id='1iSe54he4nRIYv5Q7Qo35FrlnXUwHhYCso-GWjR7gALk';s=@(@('시작',71,8),@('재무관리',6,6),@('자금일보',8839,12),@('세무사용 집계',96,20),@('계좌내역',3337,15),@('법인카드내역',5000,13),@('CMS내역',468,14),@('계정과목',80,8),@('확인요청',101,12),@('차량 데이터',1000,26),@('작성요령',183,6),@('할부',197,348),@('할부 묶음배분',62,14),@('채권추심',1200,133),@('입금내역',1274,12),@('상환원금',1201,313),@('상환이자',1201,380),@('상환수수료',1135,380),@('상환합계',959,244))}
 sw_back=@{id='17PZxK5TCdqNQDccQWWPdWBwylAu96hPIgGz42Dz5DA0';s=@(@('시작',71,8),@('백데이터',6,6),@('세는 법',44,5),@('갱신 절차',62,4),@('발굴결과',102,9),@('정합성',553,12),@('통장대조',139,12),@('계약서대조',46,8),@('한국금융 대사',132,12),@('마스터 검토',201,16),@('수납_수정전',121,182),@('신구대비표',1143,49),@('지우지마세요',1000,413),@('사용설명',134,9))}
 pr_back=@{id='18QFWdK4ovXUcEZZGoT4Qb8mcnKYMf8CPqG2iN7J8xFA';s=@(@('통장대조',139,12),@('계약서대조',46,8),@('마스터 검토',201,16),@('사용설명',134,9),@('수납_수정전',121,182))}
}
$o=[ordered]@{}
foreach($n in $books.Keys){$b=$books[$n];$ranges=@();foreach($s in $b.s){$ranges+="'$($s[0].Replace("'","''"))'!A1:$(Col $s[2])$($s[1])"};$v=G @('sheets','spreadsheets','values','batchGet') @{spreadsheetId=$b.id;ranges=$ranges;valueRenderOption='FORMATTED_VALUE'};$f=G @('sheets','spreadsheets','values','batchGet') @{spreadsheetId=$b.id;ranges=$ranges;valueRenderOption='FORMULA'};$er=@{};$fc=0;for($i=0;$i-lt$v.valueRanges.Count;$i++){$c=0;foreach($row in @($v.valueRanges[$i].values)){foreach($x in @($row)){if(([string]$x) -in @('#REF!','#N/A','#VALUE!','#DIV/0!','#NAME?','#NUM!','#ERROR!')){$c++}}};foreach($row in @($f.valueRanges[$i].values)){foreach($x in @($row)){if(([string]$x).StartsWith('=')){$fc++}}};if($c-gt0){$er[$b.s[$i][0]]=$c}};$file=G @('drive','files','get') @{fileId=$b.id;fields='id,name,modifiedTime,version'};$entry=[ordered]@{file=$file;sheetCount=$b.s.Count;formulaCount=$fc;errors=$er;errorTotal=(($er.Values|Measure-Object -Sum).Sum)};if($n -eq 'sw_fin'){foreach($target in @('계좌내역','CMS내역','입금내역')){$idx=(@($b.s|ForEach-Object{$($_[0])})).IndexOf($target);$rows=@($v.valueRanges[$idx].values);$cnt=0;for($ri=2;$ri-lt$rows.Count;$ri++){if($rows[$ri].Count-gt0 -and -not [string]::IsNullOrWhiteSpace([string]$rows[$ri][0])){$cnt++}};$entry["${target}Rows"]=$cnt}};$o[$n]=$entry}
$o|ConvertTo-Json -Depth 15
